### ISSUE TITLE
I need help seeding my database

### ISSUE THREAD

**Issue by XenoEmblems** [XenoEmblems/Safari-Zone-on-Rails#2]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

As a User I want to be able to see all 718 Pokemon in the game. 
(Set up the Seeds.rb to populate the Pokemon Table. Seed 718 Pokemon to Database.)
##### WHAT YOU ARE TRYING TO DO:

I'm working in the seeds.rb to populate the Pokemon and I'm trying to rake db:seed and I need help counting up so all the data will be collected.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

One of the errors is that the seeds.rb doesn't like the Hash that is inside the file that Im trying to grab data from. 

SyntaxError: /Users/ericxavierdoyle/Eric_Dev/safari_zone/safari_zone_app/db/seeds.rb:13: syntax error, unexpected ':', expecting =>
  "pokemon": [{
            ^
/Users/ericxavierdoyle/Eric_Dev/safari_zone/safari_zone_app/db/seeds.rb:14: syntax error, unexpected ':', expecting =>
    "id": 1,
         ^
-e:1:in `<main>'
Tasks: TOP => db:seed

I'm not sure what to do about that.
## WHAT I'VE TRIED

I tried hashing comments in the database to rationalize which functions needs numbers to manipulate the data. I was trying to set it up like how the seed.rb was in the apartment building but that was done with FFaker and I wanted to have it work like a for loop.
## QUESTION

I need to know how I can set up the seed like a for loop. I've been asking my best friend Google for help and he isn't really helping and experimenting the seed.rb is turning up fruitless. If I can get a little help I can really appreciate it.  

Sincerely,
Eric Doyle (XenoEmblems)

**Comment by XenoEmblems** [comment]
Closed for now. I'm fixing the seed.rb

**Comment by DrRobotmck** [comment]
It seems like your seed file does not like your syntax, since you are attempting to use information structured as JSON like it is a native ruby object.

- Have you tried parsing the JSON object provided into a ruby hash?
- Have you tried
