### ISSUE TITLE
I want to generate data on the Safari Div

### ISSUE THREAD

**Issue by XenoEmblems** [XenoEmblems/Safari-Zone-on-Rails#4]
CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

WHAT USER STORY YOU ARE WORKING ON:

When I visit the Safari Zone a random Pokemon should be able to render

WHAT YOU ARE TRYING TO DO:

I'm trying to pull an Ajax call and using jQuery to try to first pull the Pokemon image and then pull the rest of the data.

DETAILED DESCRIPTION OF THE BUG/ERROR:

Pokemon are "GET" but then when I try to get the image on to the div nothing happens.
rocessing by PokemonsController#show as JSON
  Parameters: {"id"=>"541"}
  Pokemon Load (0.3ms)  SELECT  "pokemons".\* FROM "pokemons" WHERE "pokemons"."id" = $1 LIMIT 1  [["id", 541]]
  Rendered pokemons/show.html.erb within layouts/application (0.3ms)
  Trainer Load (0.3ms)  SELECT  "trainers".\* FROM "trainers" WHERE "trainers"."id" = $1 LIMIT 1  [["id", 1]]
  CACHE (0.0ms)  SELECT  "trainers".\* FROM "trainers" WHERE "trainers"."id" = $1 LIMIT 1  [["id", 1]]
Completed 200 OK in 21ms (Views: 19.1ms | ActiveRecord: 0.6ms)

WHAT I'VE TRIED

Like I said I tried ajax calling and then create a RenderOne function and then set the image data into the Handlebars to try to get it to show and hopefully with some of the other data in the "pokemon/:id" pages.

QUESTION

How can I continue trying to pull information from the "pokemon/:id" show pages or from the Pokemon databases to the Safari Div

Sincerely,
Eric Doyle (XenoEmblems)

**Comment by XenoEmblems** [comment]
Also Handlebars can't be used in Ruby can they...

**Comment by WilliamfShaw** [comment]
@XenoEmblems yes for the safari page you will essentially make the same ajax call

You can however make a new non restful route in your controller to handle this view, so as not to confuse it with the show view

Handlebars should be used with backbone.
